// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookingController from "./booking_controller"
application.register("booking", BookingController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CarsController from "./cars_controller"
application.register("cars", CarsController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import StatisticsChartController from "./statistics_chart_controller"
application.register("statistics-chart", StatisticsChartController)
